// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/fzrilsh/lks-judge/internal/model"

func timeValue(t *string) string {
	if t == nil {
		return ""
	}
	if len(*t) > 5 {
		return (*t)[:5] // <input type="time"> wants HH:MM
	}
	return *t
}

func CountdownJuryPage(comp *model.Competition, saved bool, errMsg string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<a href=\"/countdown\" target=\"_blank\" class=\"btn-ghost\"><span class=\"material-symbols-outlined text-lg\" aria-hidden=\"true\">open_in_new</span> Public view</a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = PageHeader("Countdown", "Control the competition clock all participants see.").Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if saved {
				templ_7745c5c3_Err = Flash("success", "Saved. Countdown re-armed.").Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if errMsg != "" {
				templ_7745c5c3_Err = Flash("error", errMsg).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " <div class=\"grid grid-cols-1 lg:grid-cols-5 gap-4\"><section class=\"card lg:col-span-3 flex items-center justify-center min-h-[280px] relative overflow-hidden\"><div class=\"absolute inset-0 opacity-5 pointer-events-none\" aria-hidden=\"true\"><div class=\"absolute -top-24 -right-24 w-96 h-96 bg-primary rounded-full blur-3xl\"></div><div class=\"absolute -bottom-24 -left-24 w-96 h-96 bg-secondary rounded-full blur-3xl\"></div></div><div class=\"text-center relative z-10\"><p id=\"cd-clock\" class=\"text-[6rem] md:text-[8rem] leading-none font-bold tabular-nums text-on-surface\" aria-live=\"polite\">--:--:--</p><p class=\"mt-4 text-label-medium uppercase tracking-wider text-on-surface-variant\">Status: <span id=\"cd-status\" class=\"font-semibold\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(comp.Status)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `countdown_jury.templ`, Line: 38, Col: 70}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</span></p></div></section><div class=\"lg:col-span-2 flex flex-col gap-4\"><form id=\"cd-config\" method=\"POST\" action=\"/jury/countdown\" class=\"card space-y-4\" onsubmit=\"return confirm('Save configuration and re-arm the countdown?')\"><h2 class=\"text-title-medium text-on-surface\">Time Configuration</h2><div class=\"field\"><label for=\"cd-start\">Start Time</label> <input id=\"cd-start\" class=\"input\" type=\"time\" name=\"start_time\" required value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(timeValue(comp.StartTime))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `countdown_jury.templ`, Line: 47, Col: 113}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\"></div><div class=\"field\"><label for=\"cd-end\">End Time</label> <input id=\"cd-end\" class=\"input\" type=\"time\" name=\"end_time\" required value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(timeValue(comp.EndTime))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `countdown_jury.templ`, Line: 51, Col: 107}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\"></div></form><div class=\"card\"><h2 class=\"text-title-medium text-on-surface\">Controls</h2><p class=\"text-body-small text-on-surface-variant mt-1 mb-4\">Applies immediately to all participants.</p><div class=\"flex flex-wrap gap-2\"><!-- All four controls live in the DOM; countdown.js shows the pair\n\t\t\t\t\t\t     that matches the polled status so the buttons stay in sync with\n\t\t\t\t\t\t     the clock without a page reload. data-cd-show lists the statuses\n\t\t\t\t\t\t     each control is visible for. --><button type=\"submit\" form=\"cd-config\" class=\"btn-primary\" data-cd-show=\"waiting running\">SAVE</button><form method=\"POST\" action=\"/jury/countdown/resume\" data-cd-show=\"paused\"><button type=\"submit\" class=\"btn-primary\">RESUME</button></form><form method=\"POST\" action=\"/jury/countdown/pause\" data-cd-show=\"running\"><button type=\"submit\" class=\"btn-tonal\">PAUSE</button></form><form method=\"POST\" action=\"/jury/countdown/stop\" data-cd-show=\"waiting paused\" onsubmit=\"return confirm('Stop the countdown?')\"><button type=\"submit\" class=\"btn-danger\">STOP</button></form></div></div></div></div><script src=\"/static/js/countdown.js\" defer></script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = AppLayout("Countdown", "countdown").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
