// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/fzrilsh/lks-judge/internal/model"

// Leaderboard is the public ranking page. The head module columns and body rows
// are both rendered client-side by leaderboard.js from the cached JSON and
// refreshed on the ScoreUpdated WS event; this shell carries the static chrome
// (heading, table frame, fixed columns, legend) and the mount points.
func Leaderboard(comp *model.Competition) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6\"><h1 class=\"text-headline-large text-on-surface font-manrope text-center\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(comp.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `leaderboard.templ`, Line: 12, Col: 87}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h1><p class=\"text-center text-on-surface-variant text-body-medium\">WorldSkills Scale Results</p><div class=\"bg-surface-container-lowest rounded-3xl shadow-xl border border-surface-container overflow-hidden\"><div class=\"overflow-x-auto\"><table class=\"w-full text-left border-collapse whitespace-nowrap\"><thead><tr id=\"leaderboard-head\" class=\"bg-surface-container-low border-b border-surface-container\"><th class=\"py-5 px-6 text-xs uppercase tracking-wider font-bold text-outline\">Rank & Seat</th><th class=\"py-5 px-6 text-xs uppercase tracking-wider font-bold text-outline\">Participant</th><th class=\"py-5 px-6 text-xs uppercase tracking-wider font-bold text-primary text-right\">Total Score</th></tr></thead> <tbody id=\"leaderboard-body\" class=\"divide-y divide-surface-container\"><tr><td colspan=\"99\" class=\"text-center px-4 py-8 text-on-surface-variant\">Loading...</td></tr></tbody></table></div><div class=\"bg-surface-container-low px-6 py-4 border-t border-surface-container flex flex-wrap gap-4 text-xs font-medium text-outline justify-between items-center\"><div class=\"flex flex-wrap items-center gap-4\"><span class=\"flex items-center gap-1\"><span class=\"text-base\">🥇</span> Gold (1st)</span> <span class=\"flex items-center gap-1\"><span class=\"text-base\">🥈</span> Silver (2nd)</span> <span class=\"flex items-center gap-1\"><span class=\"text-base\">🥉</span> Bronze (3rd)</span> <span class=\"flex items-center gap-1\"><span class=\"inline-block w-2 h-2 rounded-full bg-blue-400\"></span> Medallion for Excellence (&gt;= 700)</span></div><div class=\"font-bold\">WSI Scale Standard Assessment</div></div></div></div><script src=\"/static/js/leaderboard.js\"></script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = GuestLayout("Leaderboard", "", "").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
